////////////////////////////////////////////////////////////////////////////////////////////////////
// Platform specific input

use ct_lib::game::{KeyState, KeyboardState, Keycode, Scancode};

/// Given a deadzone_threshold in [0.0, 1.0[
/// Outputs [-1.0, 1.0] if axisValue in [-1.0, -deadzone_threshold] u [deadzone_threshold, 1.0]
/// or 0.0 if axisValue in ]-deadzone_threshold, deadzone_threshold[
pub fn _process_gamepad_axis(
    controller: &sdl2::controller::GameController,
    axis: sdl2::controller::Axis,
    deadzone_threshold: f32,
) -> f32 {
    debug_assert!(0.0 <= deadzone_threshold && deadzone_threshold < 1.0);

    let mut axis_value = controller.axis(axis) as f32;

    const CONTROLLER_AXIS_ABSMAX_POSITIVE: f32 = 32767.0;
    const CONTROLLER_AXIS_ABSMAX_NEGATIVE: f32 = 32768.0;

    if axis_value >= 0.0 {
        axis_value /= CONTROLLER_AXIS_ABSMAX_POSITIVE;
        axis_value = if axis_value >= deadzone_threshold {
            (axis_value - deadzone_threshold) / (1.0 - deadzone_threshold)
        } else {
            0.0
        }
    } else {
        axis_value /= CONTROLLER_AXIS_ABSMAX_NEGATIVE;
        axis_value = if axis_value <= -deadzone_threshold {
            (axis_value + deadzone_threshold) / (1.0 - deadzone_threshold)
        } else {
            0.0
        }
    }

    axis_value
}

pub fn keyboardstate_create() -> KeyboardState {
    let mut keyboard = KeyboardState::new();
    for scancode_index in 0..512 {
        if let Some(sdl2_scancode) = sdl2::keyboard::Scancode::from_i32(scancode_index) {
            let scancode = scancode_to_our_scancode(sdl2_scancode);
            let keycode =
                if let Some(sdl2_keycode) = sdl2::keyboard::Keycode::from_scancode(sdl2_scancode) {
                    keycode_to_our_keycode(sdl2_keycode)
                } else {
                    Keycode::Unknown
                };

            keyboard.keys.insert(
                scancode,
                KeyState {
                    keycode,
                    scancode,
                    button: ct_lib::game::ButtonState::default(),
                },
            );
        }
    }
    keyboard
}

pub fn scancode_to_our_scancode(scancode: sdl2::keyboard::Scancode) -> Scancode {
    match scancode {
        sdl2::keyboard::Scancode::A => Scancode::A,
        sdl2::keyboard::Scancode::B => Scancode::B,
        sdl2::keyboard::Scancode::C => Scancode::C,
        sdl2::keyboard::Scancode::D => Scancode::D,
        sdl2::keyboard::Scancode::E => Scancode::E,
        sdl2::keyboard::Scancode::F => Scancode::F,
        sdl2::keyboard::Scancode::G => Scancode::G,
        sdl2::keyboard::Scancode::H => Scancode::H,
        sdl2::keyboard::Scancode::I => Scancode::I,
        sdl2::keyboard::Scancode::J => Scancode::J,
        sdl2::keyboard::Scancode::K => Scancode::K,
        sdl2::keyboard::Scancode::L => Scancode::L,
        sdl2::keyboard::Scancode::M => Scancode::M,
        sdl2::keyboard::Scancode::N => Scancode::N,
        sdl2::keyboard::Scancode::O => Scancode::O,
        sdl2::keyboard::Scancode::P => Scancode::P,
        sdl2::keyboard::Scancode::Q => Scancode::Q,
        sdl2::keyboard::Scancode::R => Scancode::R,
        sdl2::keyboard::Scancode::S => Scancode::S,
        sdl2::keyboard::Scancode::T => Scancode::T,
        sdl2::keyboard::Scancode::U => Scancode::U,
        sdl2::keyboard::Scancode::V => Scancode::V,
        sdl2::keyboard::Scancode::W => Scancode::W,
        sdl2::keyboard::Scancode::X => Scancode::X,
        sdl2::keyboard::Scancode::Y => Scancode::Y,
        sdl2::keyboard::Scancode::Z => Scancode::Z,
        sdl2::keyboard::Scancode::Num1 => Scancode::Num1,
        sdl2::keyboard::Scancode::Num2 => Scancode::Num2,
        sdl2::keyboard::Scancode::Num3 => Scancode::Num3,
        sdl2::keyboard::Scancode::Num4 => Scancode::Num4,
        sdl2::keyboard::Scancode::Num5 => Scancode::Num5,
        sdl2::keyboard::Scancode::Num6 => Scancode::Num6,
        sdl2::keyboard::Scancode::Num7 => Scancode::Num7,
        sdl2::keyboard::Scancode::Num8 => Scancode::Num8,
        sdl2::keyboard::Scancode::Num9 => Scancode::Num9,
        sdl2::keyboard::Scancode::Num0 => Scancode::Num0,
        sdl2::keyboard::Scancode::Return => Scancode::Return,
        sdl2::keyboard::Scancode::Escape => Scancode::Escape,
        sdl2::keyboard::Scancode::Backspace => Scancode::Backspace,
        sdl2::keyboard::Scancode::Tab => Scancode::Tab,
        sdl2::keyboard::Scancode::Space => Scancode::Space,
        sdl2::keyboard::Scancode::Minus => Scancode::Minus,
        sdl2::keyboard::Scancode::Equals => Scancode::Equals,
        sdl2::keyboard::Scancode::LeftBracket => Scancode::LeftBracket,
        sdl2::keyboard::Scancode::RightBracket => Scancode::RightBracket,
        sdl2::keyboard::Scancode::Backslash => Scancode::Backslash,
        sdl2::keyboard::Scancode::NonUsHash => Scancode::NonUsHash,
        sdl2::keyboard::Scancode::Semicolon => Scancode::Semicolon,
        sdl2::keyboard::Scancode::Apostrophe => Scancode::Apostrophe,
        sdl2::keyboard::Scancode::Grave => Scancode::Grave,
        sdl2::keyboard::Scancode::Comma => Scancode::Comma,
        sdl2::keyboard::Scancode::Period => Scancode::Period,
        sdl2::keyboard::Scancode::Slash => Scancode::Slash,
        sdl2::keyboard::Scancode::CapsLock => Scancode::CapsLock,
        sdl2::keyboard::Scancode::F1 => Scancode::F1,
        sdl2::keyboard::Scancode::F2 => Scancode::F2,
        sdl2::keyboard::Scancode::F3 => Scancode::F3,
        sdl2::keyboard::Scancode::F4 => Scancode::F4,
        sdl2::keyboard::Scancode::F5 => Scancode::F5,
        sdl2::keyboard::Scancode::F6 => Scancode::F6,
        sdl2::keyboard::Scancode::F7 => Scancode::F7,
        sdl2::keyboard::Scancode::F8 => Scancode::F8,
        sdl2::keyboard::Scancode::F9 => Scancode::F9,
        sdl2::keyboard::Scancode::F10 => Scancode::F10,
        sdl2::keyboard::Scancode::F11 => Scancode::F11,
        sdl2::keyboard::Scancode::F12 => Scancode::F12,
        sdl2::keyboard::Scancode::PrintScreen => Scancode::PrintScreen,
        sdl2::keyboard::Scancode::ScrollLock => Scancode::ScrollLock,
        sdl2::keyboard::Scancode::Pause => Scancode::Pause,
        sdl2::keyboard::Scancode::Insert => Scancode::Insert,
        sdl2::keyboard::Scancode::Home => Scancode::Home,
        sdl2::keyboard::Scancode::PageUp => Scancode::PageUp,
        sdl2::keyboard::Scancode::Delete => Scancode::Delete,
        sdl2::keyboard::Scancode::End => Scancode::End,
        sdl2::keyboard::Scancode::PageDown => Scancode::PageDown,
        sdl2::keyboard::Scancode::Right => Scancode::Right,
        sdl2::keyboard::Scancode::Left => Scancode::Left,
        sdl2::keyboard::Scancode::Down => Scancode::Down,
        sdl2::keyboard::Scancode::Up => Scancode::Up,
        sdl2::keyboard::Scancode::NumLockClear => Scancode::NumLockClear,
        sdl2::keyboard::Scancode::KpDivide => Scancode::KpDivide,
        sdl2::keyboard::Scancode::KpMultiply => Scancode::KpMultiply,
        sdl2::keyboard::Scancode::KpMinus => Scancode::KpMinus,
        sdl2::keyboard::Scancode::KpPlus => Scancode::KpPlus,
        sdl2::keyboard::Scancode::KpEnter => Scancode::KpEnter,
        sdl2::keyboard::Scancode::Kp1 => Scancode::Kp1,
        sdl2::keyboard::Scancode::Kp2 => Scancode::Kp2,
        sdl2::keyboard::Scancode::Kp3 => Scancode::Kp3,
        sdl2::keyboard::Scancode::Kp4 => Scancode::Kp4,
        sdl2::keyboard::Scancode::Kp5 => Scancode::Kp5,
        sdl2::keyboard::Scancode::Kp6 => Scancode::Kp6,
        sdl2::keyboard::Scancode::Kp7 => Scancode::Kp7,
        sdl2::keyboard::Scancode::Kp8 => Scancode::Kp8,
        sdl2::keyboard::Scancode::Kp9 => Scancode::Kp9,
        sdl2::keyboard::Scancode::Kp0 => Scancode::Kp0,
        sdl2::keyboard::Scancode::KpPeriod => Scancode::KpPeriod,
        sdl2::keyboard::Scancode::NonUsBackslash => Scancode::NonUsBackslash,
        sdl2::keyboard::Scancode::Application => Scancode::Application,
        sdl2::keyboard::Scancode::Power => Scancode::Power,
        sdl2::keyboard::Scancode::KpEquals => Scancode::KpEquals,
        sdl2::keyboard::Scancode::F13 => Scancode::F13,
        sdl2::keyboard::Scancode::F14 => Scancode::F14,
        sdl2::keyboard::Scancode::F15 => Scancode::F15,
        sdl2::keyboard::Scancode::F16 => Scancode::F16,
        sdl2::keyboard::Scancode::F17 => Scancode::F17,
        sdl2::keyboard::Scancode::F18 => Scancode::F18,
        sdl2::keyboard::Scancode::F19 => Scancode::F19,
        sdl2::keyboard::Scancode::F20 => Scancode::F20,
        sdl2::keyboard::Scancode::F21 => Scancode::F21,
        sdl2::keyboard::Scancode::F22 => Scancode::F22,
        sdl2::keyboard::Scancode::F23 => Scancode::F23,
        sdl2::keyboard::Scancode::F24 => Scancode::F24,
        sdl2::keyboard::Scancode::Execute => Scancode::Execute,
        sdl2::keyboard::Scancode::Help => Scancode::Help,
        sdl2::keyboard::Scancode::Menu => Scancode::Menu,
        sdl2::keyboard::Scancode::Select => Scancode::Select,
        sdl2::keyboard::Scancode::Stop => Scancode::Stop,
        sdl2::keyboard::Scancode::Again => Scancode::Again,
        sdl2::keyboard::Scancode::Undo => Scancode::Undo,
        sdl2::keyboard::Scancode::Cut => Scancode::Cut,
        sdl2::keyboard::Scancode::Copy => Scancode::Copy,
        sdl2::keyboard::Scancode::Paste => Scancode::Paste,
        sdl2::keyboard::Scancode::Find => Scancode::Find,
        sdl2::keyboard::Scancode::Mute => Scancode::Mute,
        sdl2::keyboard::Scancode::VolumeUp => Scancode::VolumeUp,
        sdl2::keyboard::Scancode::VolumeDown => Scancode::VolumeDown,
        sdl2::keyboard::Scancode::KpComma => Scancode::KpComma,
        sdl2::keyboard::Scancode::KpEqualsAS400 => Scancode::KpEqualsAS400,
        sdl2::keyboard::Scancode::International1 => Scancode::International1,
        sdl2::keyboard::Scancode::International2 => Scancode::International2,
        sdl2::keyboard::Scancode::International3 => Scancode::International3,
        sdl2::keyboard::Scancode::International4 => Scancode::International4,
        sdl2::keyboard::Scancode::International5 => Scancode::International5,
        sdl2::keyboard::Scancode::International6 => Scancode::International6,
        sdl2::keyboard::Scancode::International7 => Scancode::International7,
        sdl2::keyboard::Scancode::International8 => Scancode::International8,
        sdl2::keyboard::Scancode::International9 => Scancode::International9,
        sdl2::keyboard::Scancode::Lang1 => Scancode::Lang1,
        sdl2::keyboard::Scancode::Lang2 => Scancode::Lang2,
        sdl2::keyboard::Scancode::Lang3 => Scancode::Lang3,
        sdl2::keyboard::Scancode::Lang4 => Scancode::Lang4,
        sdl2::keyboard::Scancode::Lang5 => Scancode::Lang5,
        sdl2::keyboard::Scancode::Lang6 => Scancode::Lang6,
        sdl2::keyboard::Scancode::Lang7 => Scancode::Lang7,
        sdl2::keyboard::Scancode::Lang8 => Scancode::Lang8,
        sdl2::keyboard::Scancode::Lang9 => Scancode::Lang9,
        sdl2::keyboard::Scancode::AltErase => Scancode::AltErase,
        sdl2::keyboard::Scancode::SysReq => Scancode::SysReq,
        sdl2::keyboard::Scancode::Cancel => Scancode::Cancel,
        sdl2::keyboard::Scancode::Clear => Scancode::Clear,
        sdl2::keyboard::Scancode::Prior => Scancode::Prior,
        sdl2::keyboard::Scancode::Return2 => Scancode::Return2,
        sdl2::keyboard::Scancode::Separator => Scancode::Separator,
        sdl2::keyboard::Scancode::Out => Scancode::Out,
        sdl2::keyboard::Scancode::Oper => Scancode::Oper,
        sdl2::keyboard::Scancode::ClearAgain => Scancode::ClearAgain,
        sdl2::keyboard::Scancode::CrSel => Scancode::CrSel,
        sdl2::keyboard::Scancode::ExSel => Scancode::ExSel,
        sdl2::keyboard::Scancode::Kp00 => Scancode::Kp00,
        sdl2::keyboard::Scancode::Kp000 => Scancode::Kp000,
        sdl2::keyboard::Scancode::ThousandsSeparator => Scancode::ThousandsSeparator,
        sdl2::keyboard::Scancode::DecimalSeparator => Scancode::DecimalSeparator,
        sdl2::keyboard::Scancode::CurrencyUnit => Scancode::CurrencyUnit,
        sdl2::keyboard::Scancode::CurrencySubUnit => Scancode::CurrencySubUnit,
        sdl2::keyboard::Scancode::KpLeftParen => Scancode::KpLeftParen,
        sdl2::keyboard::Scancode::KpRightParen => Scancode::KpRightParen,
        sdl2::keyboard::Scancode::KpLeftBrace => Scancode::KpLeftBrace,
        sdl2::keyboard::Scancode::KpRightBrace => Scancode::KpRightBrace,
        sdl2::keyboard::Scancode::KpTab => Scancode::KpTab,
        sdl2::keyboard::Scancode::KpBackspace => Scancode::KpBackspace,
        sdl2::keyboard::Scancode::KpA => Scancode::KpA,
        sdl2::keyboard::Scancode::KpB => Scancode::KpB,
        sdl2::keyboard::Scancode::KpC => Scancode::KpC,
        sdl2::keyboard::Scancode::KpD => Scancode::KpD,
        sdl2::keyboard::Scancode::KpE => Scancode::KpE,
        sdl2::keyboard::Scancode::KpF => Scancode::KpF,
        sdl2::keyboard::Scancode::KpXor => Scancode::KpXor,
        sdl2::keyboard::Scancode::KpPower => Scancode::KpPower,
        sdl2::keyboard::Scancode::KpPercent => Scancode::KpPercent,
        sdl2::keyboard::Scancode::KpLess => Scancode::KpLess,
        sdl2::keyboard::Scancode::KpGreater => Scancode::KpGreater,
        sdl2::keyboard::Scancode::KpAmpersand => Scancode::KpAmpersand,
        sdl2::keyboard::Scancode::KpDblAmpersand => Scancode::KpDblAmpersand,
        sdl2::keyboard::Scancode::KpVerticalBar => Scancode::KpVerticalBar,
        sdl2::keyboard::Scancode::KpDblVerticalBar => Scancode::KpDblVerticalBar,
        sdl2::keyboard::Scancode::KpColon => Scancode::KpColon,
        sdl2::keyboard::Scancode::KpHash => Scancode::KpHash,
        sdl2::keyboard::Scancode::KpSpace => Scancode::KpSpace,
        sdl2::keyboard::Scancode::KpAt => Scancode::KpAt,
        sdl2::keyboard::Scancode::KpExclam => Scancode::KpExclam,
        sdl2::keyboard::Scancode::KpMemStore => Scancode::KpMemStore,
        sdl2::keyboard::Scancode::KpMemRecall => Scancode::KpMemRecall,
        sdl2::keyboard::Scancode::KpMemClear => Scancode::KpMemClear,
        sdl2::keyboard::Scancode::KpMemAdd => Scancode::KpMemAdd,
        sdl2::keyboard::Scancode::KpMemSubtract => Scancode::KpMemSubtract,
        sdl2::keyboard::Scancode::KpMemMultiply => Scancode::KpMemMultiply,
        sdl2::keyboard::Scancode::KpMemDivide => Scancode::KpMemDivide,
        sdl2::keyboard::Scancode::KpPlusMinus => Scancode::KpPlusMinus,
        sdl2::keyboard::Scancode::KpClear => Scancode::KpClear,
        sdl2::keyboard::Scancode::KpClearEntry => Scancode::KpClearEntry,
        sdl2::keyboard::Scancode::KpBinary => Scancode::KpBinary,
        sdl2::keyboard::Scancode::KpOctal => Scancode::KpOctal,
        sdl2::keyboard::Scancode::KpDecimal => Scancode::KpDecimal,
        sdl2::keyboard::Scancode::KpHexadecimal => Scancode::KpHexadecimal,
        sdl2::keyboard::Scancode::LCtrl => Scancode::LCtrl,
        sdl2::keyboard::Scancode::LShift => Scancode::LShift,
        sdl2::keyboard::Scancode::LAlt => Scancode::LAlt,
        sdl2::keyboard::Scancode::LGui => Scancode::LGui,
        sdl2::keyboard::Scancode::RCtrl => Scancode::RCtrl,
        sdl2::keyboard::Scancode::RShift => Scancode::RShift,
        sdl2::keyboard::Scancode::RAlt => Scancode::RAlt,
        sdl2::keyboard::Scancode::RGui => Scancode::RGui,
        sdl2::keyboard::Scancode::Mode => Scancode::Mode,
        sdl2::keyboard::Scancode::AudioNext => Scancode::AudioNext,
        sdl2::keyboard::Scancode::AudioPrev => Scancode::AudioPrev,
        sdl2::keyboard::Scancode::AudioStop => Scancode::AudioStop,
        sdl2::keyboard::Scancode::AudioPlay => Scancode::AudioPlay,
        sdl2::keyboard::Scancode::AudioMute => Scancode::AudioMute,
        sdl2::keyboard::Scancode::MediaSelect => Scancode::MediaSelect,
        sdl2::keyboard::Scancode::Www => Scancode::Www,
        sdl2::keyboard::Scancode::Mail => Scancode::Mail,
        sdl2::keyboard::Scancode::Calculator => Scancode::Calculator,
        sdl2::keyboard::Scancode::Computer => Scancode::Computer,
        sdl2::keyboard::Scancode::AcSearch => Scancode::AcSearch,
        sdl2::keyboard::Scancode::AcHome => Scancode::AcHome,
        sdl2::keyboard::Scancode::AcBack => Scancode::AcBack,
        sdl2::keyboard::Scancode::AcForward => Scancode::AcForward,
        sdl2::keyboard::Scancode::AcStop => Scancode::AcStop,
        sdl2::keyboard::Scancode::AcRefresh => Scancode::AcRefresh,
        sdl2::keyboard::Scancode::AcBookmarks => Scancode::AcBookmarks,
        sdl2::keyboard::Scancode::BrightnessDown => Scancode::BrightnessDown,
        sdl2::keyboard::Scancode::BrightnessUp => Scancode::BrightnessUp,
        sdl2::keyboard::Scancode::DisplaySwitch => Scancode::DisplaySwitch,
        sdl2::keyboard::Scancode::KbdIllumToggle => Scancode::KbdIllumToggle,
        sdl2::keyboard::Scancode::KbdIllumDown => Scancode::KbdIllumDown,
        sdl2::keyboard::Scancode::KbdIllumUp => Scancode::KbdIllumUp,
        sdl2::keyboard::Scancode::Eject => Scancode::Eject,
        sdl2::keyboard::Scancode::Sleep => Scancode::Sleep,
        sdl2::keyboard::Scancode::App1 => Scancode::App1,
        sdl2::keyboard::Scancode::App2 => Scancode::App2,
        sdl2::keyboard::Scancode::Num => Scancode::Num,
    }
}
pub fn keycode_to_our_keycode(keycode: sdl2::keyboard::Keycode) -> Keycode {
    match keycode {
        sdl2::keyboard::Keycode::Backspace => Keycode::Backspace,
        sdl2::keyboard::Keycode::Tab => Keycode::Tab,
        sdl2::keyboard::Keycode::Return => Keycode::Return,
        sdl2::keyboard::Keycode::Escape => Keycode::Escape,
        sdl2::keyboard::Keycode::Space => Keycode::Space,
        sdl2::keyboard::Keycode::Exclaim => Keycode::Exclaim,
        sdl2::keyboard::Keycode::Quotedbl => Keycode::Quotedbl,
        sdl2::keyboard::Keycode::Hash => Keycode::Hash,
        sdl2::keyboard::Keycode::Dollar => Keycode::Dollar,
        sdl2::keyboard::Keycode::Percent => Keycode::Percent,
        sdl2::keyboard::Keycode::Ampersand => Keycode::Ampersand,
        sdl2::keyboard::Keycode::Quote => Keycode::Quote,
        sdl2::keyboard::Keycode::LeftParen => Keycode::LeftParen,
        sdl2::keyboard::Keycode::RightParen => Keycode::RightParen,
        sdl2::keyboard::Keycode::Asterisk => Keycode::Asterisk,
        sdl2::keyboard::Keycode::Plus => Keycode::Plus,
        sdl2::keyboard::Keycode::Comma => Keycode::Comma,
        sdl2::keyboard::Keycode::Minus => Keycode::Minus,
        sdl2::keyboard::Keycode::Period => Keycode::Period,
        sdl2::keyboard::Keycode::Slash => Keycode::Slash,
        sdl2::keyboard::Keycode::Num0 => Keycode::Num0,
        sdl2::keyboard::Keycode::Num1 => Keycode::Num1,
        sdl2::keyboard::Keycode::Num2 => Keycode::Num2,
        sdl2::keyboard::Keycode::Num3 => Keycode::Num3,
        sdl2::keyboard::Keycode::Num4 => Keycode::Num4,
        sdl2::keyboard::Keycode::Num5 => Keycode::Num5,
        sdl2::keyboard::Keycode::Num6 => Keycode::Num6,
        sdl2::keyboard::Keycode::Num7 => Keycode::Num7,
        sdl2::keyboard::Keycode::Num8 => Keycode::Num8,
        sdl2::keyboard::Keycode::Num9 => Keycode::Num9,
        sdl2::keyboard::Keycode::Colon => Keycode::Colon,
        sdl2::keyboard::Keycode::Semicolon => Keycode::Semicolon,
        sdl2::keyboard::Keycode::Less => Keycode::Less,
        sdl2::keyboard::Keycode::Equals => Keycode::Equals,
        sdl2::keyboard::Keycode::Greater => Keycode::Greater,
        sdl2::keyboard::Keycode::Question => Keycode::Question,
        sdl2::keyboard::Keycode::At => Keycode::At,
        sdl2::keyboard::Keycode::LeftBracket => Keycode::LeftBracket,
        sdl2::keyboard::Keycode::Backslash => Keycode::Backslash,
        sdl2::keyboard::Keycode::RightBracket => Keycode::RightBracket,
        sdl2::keyboard::Keycode::Caret => Keycode::Caret,
        sdl2::keyboard::Keycode::Underscore => Keycode::Underscore,
        sdl2::keyboard::Keycode::Backquote => Keycode::Backquote,
        sdl2::keyboard::Keycode::A => Keycode::A,
        sdl2::keyboard::Keycode::B => Keycode::B,
        sdl2::keyboard::Keycode::C => Keycode::C,
        sdl2::keyboard::Keycode::D => Keycode::D,
        sdl2::keyboard::Keycode::E => Keycode::E,
        sdl2::keyboard::Keycode::F => Keycode::F,
        sdl2::keyboard::Keycode::G => Keycode::G,
        sdl2::keyboard::Keycode::H => Keycode::H,
        sdl2::keyboard::Keycode::I => Keycode::I,
        sdl2::keyboard::Keycode::J => Keycode::J,
        sdl2::keyboard::Keycode::K => Keycode::K,
        sdl2::keyboard::Keycode::L => Keycode::L,
        sdl2::keyboard::Keycode::M => Keycode::M,
        sdl2::keyboard::Keycode::N => Keycode::N,
        sdl2::keyboard::Keycode::O => Keycode::O,
        sdl2::keyboard::Keycode::P => Keycode::P,
        sdl2::keyboard::Keycode::Q => Keycode::Q,
        sdl2::keyboard::Keycode::R => Keycode::R,
        sdl2::keyboard::Keycode::S => Keycode::S,
        sdl2::keyboard::Keycode::T => Keycode::T,
        sdl2::keyboard::Keycode::U => Keycode::U,
        sdl2::keyboard::Keycode::V => Keycode::V,
        sdl2::keyboard::Keycode::W => Keycode::W,
        sdl2::keyboard::Keycode::X => Keycode::X,
        sdl2::keyboard::Keycode::Y => Keycode::Y,
        sdl2::keyboard::Keycode::Z => Keycode::Z,
        sdl2::keyboard::Keycode::Delete => Keycode::Delete,
        sdl2::keyboard::Keycode::CapsLock => Keycode::CapsLock,
        sdl2::keyboard::Keycode::F1 => Keycode::F1,
        sdl2::keyboard::Keycode::F2 => Keycode::F2,
        sdl2::keyboard::Keycode::F3 => Keycode::F3,
        sdl2::keyboard::Keycode::F4 => Keycode::F4,
        sdl2::keyboard::Keycode::F5 => Keycode::F5,
        sdl2::keyboard::Keycode::F6 => Keycode::F6,
        sdl2::keyboard::Keycode::F7 => Keycode::F7,
        sdl2::keyboard::Keycode::F8 => Keycode::F8,
        sdl2::keyboard::Keycode::F9 => Keycode::F9,
        sdl2::keyboard::Keycode::F10 => Keycode::F10,
        sdl2::keyboard::Keycode::F11 => Keycode::F11,
        sdl2::keyboard::Keycode::F12 => Keycode::F12,
        sdl2::keyboard::Keycode::PrintScreen => Keycode::PrintScreen,
        sdl2::keyboard::Keycode::ScrollLock => Keycode::ScrollLock,
        sdl2::keyboard::Keycode::Pause => Keycode::Pause,
        sdl2::keyboard::Keycode::Insert => Keycode::Insert,
        sdl2::keyboard::Keycode::Home => Keycode::Home,
        sdl2::keyboard::Keycode::PageUp => Keycode::PageUp,
        sdl2::keyboard::Keycode::End => Keycode::End,
        sdl2::keyboard::Keycode::PageDown => Keycode::PageDown,
        sdl2::keyboard::Keycode::Right => Keycode::Right,
        sdl2::keyboard::Keycode::Left => Keycode::Left,
        sdl2::keyboard::Keycode::Down => Keycode::Down,
        sdl2::keyboard::Keycode::Up => Keycode::Up,
        sdl2::keyboard::Keycode::NumLockClear => Keycode::NumLockClear,
        sdl2::keyboard::Keycode::KpDivide => Keycode::KpDivide,
        sdl2::keyboard::Keycode::KpMultiply => Keycode::KpMultiply,
        sdl2::keyboard::Keycode::KpMinus => Keycode::KpMinus,
        sdl2::keyboard::Keycode::KpPlus => Keycode::KpPlus,
        sdl2::keyboard::Keycode::KpEnter => Keycode::KpEnter,
        sdl2::keyboard::Keycode::Kp1 => Keycode::Kp1,
        sdl2::keyboard::Keycode::Kp2 => Keycode::Kp2,
        sdl2::keyboard::Keycode::Kp3 => Keycode::Kp3,
        sdl2::keyboard::Keycode::Kp4 => Keycode::Kp4,
        sdl2::keyboard::Keycode::Kp5 => Keycode::Kp5,
        sdl2::keyboard::Keycode::Kp6 => Keycode::Kp6,
        sdl2::keyboard::Keycode::Kp7 => Keycode::Kp7,
        sdl2::keyboard::Keycode::Kp8 => Keycode::Kp8,
        sdl2::keyboard::Keycode::Kp9 => Keycode::Kp9,
        sdl2::keyboard::Keycode::Kp0 => Keycode::Kp0,
        sdl2::keyboard::Keycode::KpPeriod => Keycode::KpPeriod,
        sdl2::keyboard::Keycode::Application => Keycode::Application,
        sdl2::keyboard::Keycode::Power => Keycode::Power,
        sdl2::keyboard::Keycode::KpEquals => Keycode::KpEquals,
        sdl2::keyboard::Keycode::F13 => Keycode::F13,
        sdl2::keyboard::Keycode::F14 => Keycode::F14,
        sdl2::keyboard::Keycode::F15 => Keycode::F15,
        sdl2::keyboard::Keycode::F16 => Keycode::F16,
        sdl2::keyboard::Keycode::F17 => Keycode::F17,
        sdl2::keyboard::Keycode::F18 => Keycode::F18,
        sdl2::keyboard::Keycode::F19 => Keycode::F19,
        sdl2::keyboard::Keycode::F20 => Keycode::F20,
        sdl2::keyboard::Keycode::F21 => Keycode::F21,
        sdl2::keyboard::Keycode::F22 => Keycode::F22,
        sdl2::keyboard::Keycode::F23 => Keycode::F23,
        sdl2::keyboard::Keycode::F24 => Keycode::F24,
        sdl2::keyboard::Keycode::Execute => Keycode::Execute,
        sdl2::keyboard::Keycode::Help => Keycode::Help,
        sdl2::keyboard::Keycode::Menu => Keycode::Menu,
        sdl2::keyboard::Keycode::Select => Keycode::Select,
        sdl2::keyboard::Keycode::Stop => Keycode::Stop,
        sdl2::keyboard::Keycode::Again => Keycode::Again,
        sdl2::keyboard::Keycode::Undo => Keycode::Undo,
        sdl2::keyboard::Keycode::Cut => Keycode::Cut,
        sdl2::keyboard::Keycode::Copy => Keycode::Copy,
        sdl2::keyboard::Keycode::Paste => Keycode::Paste,
        sdl2::keyboard::Keycode::Find => Keycode::Find,
        sdl2::keyboard::Keycode::Mute => Keycode::Mute,
        sdl2::keyboard::Keycode::VolumeUp => Keycode::VolumeUp,
        sdl2::keyboard::Keycode::VolumeDown => Keycode::VolumeDown,
        sdl2::keyboard::Keycode::KpComma => Keycode::KpComma,
        sdl2::keyboard::Keycode::KpEqualsAS400 => Keycode::KpEqualsAS400,
        sdl2::keyboard::Keycode::AltErase => Keycode::AltErase,
        sdl2::keyboard::Keycode::Sysreq => Keycode::Sysreq,
        sdl2::keyboard::Keycode::Cancel => Keycode::Cancel,
        sdl2::keyboard::Keycode::Clear => Keycode::Clear,
        sdl2::keyboard::Keycode::Prior => Keycode::Prior,
        sdl2::keyboard::Keycode::Return2 => Keycode::Return2,
        sdl2::keyboard::Keycode::Separator => Keycode::Separator,
        sdl2::keyboard::Keycode::Out => Keycode::Out,
        sdl2::keyboard::Keycode::Oper => Keycode::Oper,
        sdl2::keyboard::Keycode::ClearAgain => Keycode::ClearAgain,
        sdl2::keyboard::Keycode::CrSel => Keycode::CrSel,
        sdl2::keyboard::Keycode::ExSel => Keycode::ExSel,
        sdl2::keyboard::Keycode::Kp00 => Keycode::Kp00,
        sdl2::keyboard::Keycode::Kp000 => Keycode::Kp000,
        sdl2::keyboard::Keycode::ThousandsSeparator => Keycode::ThousandsSeparator,
        sdl2::keyboard::Keycode::DecimalSeparator => Keycode::DecimalSeparator,
        sdl2::keyboard::Keycode::CurrencyUnit => Keycode::CurrencyUnit,
        sdl2::keyboard::Keycode::CurrencySubUnit => Keycode::CurrencySubUnit,
        sdl2::keyboard::Keycode::KpLeftParen => Keycode::KpLeftParen,
        sdl2::keyboard::Keycode::KpRightParen => Keycode::KpRightParen,
        sdl2::keyboard::Keycode::KpLeftBrace => Keycode::KpLeftBrace,
        sdl2::keyboard::Keycode::KpRightBrace => Keycode::KpRightBrace,
        sdl2::keyboard::Keycode::KpTab => Keycode::KpTab,
        sdl2::keyboard::Keycode::KpBackspace => Keycode::KpBackspace,
        sdl2::keyboard::Keycode::KpA => Keycode::KpA,
        sdl2::keyboard::Keycode::KpB => Keycode::KpB,
        sdl2::keyboard::Keycode::KpC => Keycode::KpC,
        sdl2::keyboard::Keycode::KpD => Keycode::KpD,
        sdl2::keyboard::Keycode::KpE => Keycode::KpE,
        sdl2::keyboard::Keycode::KpF => Keycode::KpF,
        sdl2::keyboard::Keycode::KpXor => Keycode::KpXor,
        sdl2::keyboard::Keycode::KpPower => Keycode::KpPower,
        sdl2::keyboard::Keycode::KpPercent => Keycode::KpPercent,
        sdl2::keyboard::Keycode::KpLess => Keycode::KpLess,
        sdl2::keyboard::Keycode::KpGreater => Keycode::KpGreater,
        sdl2::keyboard::Keycode::KpAmpersand => Keycode::KpAmpersand,
        sdl2::keyboard::Keycode::KpDblAmpersand => Keycode::KpDblAmpersand,
        sdl2::keyboard::Keycode::KpVerticalBar => Keycode::KpVerticalBar,
        sdl2::keyboard::Keycode::KpDblVerticalBar => Keycode::KpDblVerticalBar,
        sdl2::keyboard::Keycode::KpColon => Keycode::KpColon,
        sdl2::keyboard::Keycode::KpHash => Keycode::KpHash,
        sdl2::keyboard::Keycode::KpSpace => Keycode::KpSpace,
        sdl2::keyboard::Keycode::KpAt => Keycode::KpAt,
        sdl2::keyboard::Keycode::KpExclam => Keycode::KpExclam,
        sdl2::keyboard::Keycode::KpMemStore => Keycode::KpMemStore,
        sdl2::keyboard::Keycode::KpMemRecall => Keycode::KpMemRecall,
        sdl2::keyboard::Keycode::KpMemClear => Keycode::KpMemClear,
        sdl2::keyboard::Keycode::KpMemAdd => Keycode::KpMemAdd,
        sdl2::keyboard::Keycode::KpMemSubtract => Keycode::KpMemSubtract,
        sdl2::keyboard::Keycode::KpMemMultiply => Keycode::KpMemMultiply,
        sdl2::keyboard::Keycode::KpMemDivide => Keycode::KpMemDivide,
        sdl2::keyboard::Keycode::KpPlusMinus => Keycode::KpPlusMinus,
        sdl2::keyboard::Keycode::KpClear => Keycode::KpClear,
        sdl2::keyboard::Keycode::KpClearEntry => Keycode::KpClearEntry,
        sdl2::keyboard::Keycode::KpBinary => Keycode::KpBinary,
        sdl2::keyboard::Keycode::KpOctal => Keycode::KpOctal,
        sdl2::keyboard::Keycode::KpDecimal => Keycode::KpDecimal,
        sdl2::keyboard::Keycode::KpHexadecimal => Keycode::KpHexadecimal,
        sdl2::keyboard::Keycode::LCtrl => Keycode::LCtrl,
        sdl2::keyboard::Keycode::LShift => Keycode::LShift,
        sdl2::keyboard::Keycode::LAlt => Keycode::LAlt,
        sdl2::keyboard::Keycode::LGui => Keycode::LGui,
        sdl2::keyboard::Keycode::RCtrl => Keycode::RCtrl,
        sdl2::keyboard::Keycode::RShift => Keycode::RShift,
        sdl2::keyboard::Keycode::RAlt => Keycode::RAlt,
        sdl2::keyboard::Keycode::RGui => Keycode::RGui,
        sdl2::keyboard::Keycode::Mode => Keycode::Mode,
        sdl2::keyboard::Keycode::AudioNext => Keycode::AudioNext,
        sdl2::keyboard::Keycode::AudioPrev => Keycode::AudioPrev,
        sdl2::keyboard::Keycode::AudioStop => Keycode::AudioStop,
        sdl2::keyboard::Keycode::AudioPlay => Keycode::AudioPlay,
        sdl2::keyboard::Keycode::AudioMute => Keycode::AudioMute,
        sdl2::keyboard::Keycode::MediaSelect => Keycode::MediaSelect,
        sdl2::keyboard::Keycode::Www => Keycode::Www,
        sdl2::keyboard::Keycode::Mail => Keycode::Mail,
        sdl2::keyboard::Keycode::Calculator => Keycode::Calculator,
        sdl2::keyboard::Keycode::Computer => Keycode::Computer,
        sdl2::keyboard::Keycode::AcSearch => Keycode::AcSearch,
        sdl2::keyboard::Keycode::AcHome => Keycode::AcHome,
        sdl2::keyboard::Keycode::AcBack => Keycode::AcBack,
        sdl2::keyboard::Keycode::AcForward => Keycode::AcForward,
        sdl2::keyboard::Keycode::AcStop => Keycode::AcStop,
        sdl2::keyboard::Keycode::AcRefresh => Keycode::AcRefresh,
        sdl2::keyboard::Keycode::AcBookmarks => Keycode::AcBookmarks,
        sdl2::keyboard::Keycode::BrightnessDown => Keycode::BrightnessDown,
        sdl2::keyboard::Keycode::BrightnessUp => Keycode::BrightnessUp,
        sdl2::keyboard::Keycode::DisplaySwitch => Keycode::DisplaySwitch,
        sdl2::keyboard::Keycode::KbdIllumToggle => Keycode::KbdIllumToggle,
        sdl2::keyboard::Keycode::KbdIllumDown => Keycode::KbdIllumDown,
        sdl2::keyboard::Keycode::KbdIllumUp => Keycode::KbdIllumUp,
        sdl2::keyboard::Keycode::Eject => Keycode::Eject,
        sdl2::keyboard::Keycode::Sleep => Keycode::Sleep,
    }
}
