////////////////////////////////////////////////////////////////////////////////////////////////////
// Platform specific input

use ct_lib::game::{Keycode, Scancode};

pub fn scancode_to_our_scancode(scancode: &str) -> Scancode {
    match scancode {
        "Digit1" => Scancode::Digit1,
        "Digit2" => Scancode::Digit2,
        "Digit3" => Scancode::Digit3,
        "Digit4" => Scancode::Digit4,
        "Digit5" => Scancode::Digit5,
        "Digit6" => Scancode::Digit6,
        "Digit7" => Scancode::Digit7,
        "Digit8" => Scancode::Digit8,
        "Digit9" => Scancode::Digit9,
        "Digit0" => Scancode::Digit0,

        "KeyA" => Scancode::A,
        "KeyB" => Scancode::B,
        "KeyC" => Scancode::C,
        "KeyD" => Scancode::D,
        "KeyE" => Scancode::E,
        "KeyF" => Scancode::F,
        "KeyG" => Scancode::G,
        "KeyH" => Scancode::H,
        "KeyI" => Scancode::I,
        "KeyJ" => Scancode::J,
        "KeyK" => Scancode::K,
        "KeyL" => Scancode::L,
        "KeyM" => Scancode::M,
        "KeyN" => Scancode::N,
        "KeyO" => Scancode::O,
        "KeyP" => Scancode::P,
        "KeyQ" => Scancode::Q,
        "KeyR" => Scancode::R,
        "KeyS" => Scancode::S,
        "KeyT" => Scancode::T,
        "KeyU" => Scancode::U,
        "KeyV" => Scancode::V,
        "KeyW" => Scancode::W,
        "KeyX" => Scancode::X,
        "KeyY" => Scancode::Y,
        "KeyZ" => Scancode::Z,

        "AudioVolumeMute" => Scancode::AudioVolumeMute,
        "VolumeUp" | "AudioVolumeUp" => Scancode::AudioVolumeUp,
        "VolumeDown" | "AudioVolumeDown" => Scancode::AudioVolumeDown,

        "Equal" => Scancode::Equal,
        "Minus" => Scancode::Minus,
        "BracketRight" => Scancode::BracketRight,
        "BracketLeft" => Scancode::BracketLeft,
        "Slash" => Scancode::Slash,
        "Backslash" => Scancode::Backslash,

        "Escape" => Scancode::Escape,
        "Enter" => Scancode::Enter,
        "Tab" => Scancode::Tab,
        "Space" => Scancode::Space,
        "Backspace" => Scancode::Backspace,

        "Quote" => Scancode::Quote,
        "Backquote" => Scancode::Backquote,
        "Semicolon" => Scancode::Semicolon,
        "Comma" => Scancode::Comma,
        "Period" => Scancode::Period,

        "CapsLock" => Scancode::CapsLock,
        "MetaLeft" | "OsLeft" => Scancode::MetaLeft,
        "MetaRight" | "OsRight" => Scancode::MetaRight,
        "ShiftLeft" => Scancode::ShiftLeft,
        "ShiftRight" => Scancode::ShiftRight,
        "AltLeft" => Scancode::AltLeft,
        "AltRight" => Scancode::AltRight,
        "ControlLeft" => Scancode::ControlLeft,
        "ControlRight" => Scancode::ControlRight,
        "ContextMenu" => Scancode::ContextMenu,

        "F1" => Scancode::F1,
        "F2" => Scancode::F2,
        "F3" => Scancode::F3,
        "F4" => Scancode::F4,
        "F5" => Scancode::F5,
        "F6" => Scancode::F6,
        "F7" => Scancode::F7,
        "F8" => Scancode::F8,
        "F9" => Scancode::F9,
        "F10" => Scancode::F10,
        "F11" => Scancode::F11,
        "F12" => Scancode::F12,

        "NumLock" => Scancode::Numlock,
        "NumpadMultiply" => Scancode::NumpadMultiply,
        "NumpadAdd" => Scancode::NumpadAdd,
        "NumpadDivide" => Scancode::NumpadDivide,
        "NumpadEnter" => Scancode::NumpadEnter,
        "NumpadSubtract" => Scancode::NumpadSubtract,
        "NumpadEqual" => Scancode::NumpadEqual,
        "NumpadComma" => Scancode::NumpadComma,
        "NumpadDecimal" => Scancode::NumpadDecimal,

        "Numpad0" => Scancode::Numpad0,
        "Numpad1" => Scancode::Numpad1,
        "Numpad2" => Scancode::Numpad2,
        "Numpad3" => Scancode::Numpad3,
        "Numpad4" => Scancode::Numpad4,
        "Numpad5" => Scancode::Numpad5,
        "Numpad6" => Scancode::Numpad6,
        "Numpad7" => Scancode::Numpad7,
        "Numpad8" => Scancode::Numpad8,
        "Numpad9" => Scancode::Numpad9,

        "ScrollLock" => Scancode::ScrollLock,
        "PrintScreen" => Scancode::PrintScreen,
        "Pause" => Scancode::Pause,

        "Home" => Scancode::Home,
        "Delete" => Scancode::Delete,
        "End" => Scancode::End,
        "PageUp" => Scancode::PageUp,
        "PageDown" => Scancode::PageDown,
        "Insert" => Scancode::Insert,

        "ArrowLeft" => Scancode::ArrowLeft,
        "ArrowUp" => Scancode::ArrowUp,
        "ArrowRight" => Scancode::ArrowRight,
        "ArrowDown" => Scancode::ArrowDown,

        _ => Scancode::Unidentified,
    }
}

pub fn keycode_to_our_keycode(keycode: &str, scancode: Scancode) -> Keycode {
    match scancode {
        // Use scancode where possible
        Scancode::Digit1 => Keycode::Digit1,
        Scancode::Digit2 => Keycode::Digit2,
        Scancode::Digit3 => Keycode::Digit3,
        Scancode::Digit4 => Keycode::Digit4,
        Scancode::Digit5 => Keycode::Digit5,
        Scancode::Digit6 => Keycode::Digit6,
        Scancode::Digit7 => Keycode::Digit7,
        Scancode::Digit8 => Keycode::Digit8,
        Scancode::Digit9 => Keycode::Digit9,
        Scancode::Digit0 => Keycode::Digit0,

        Scancode::AudioVolumeUp => Keycode::AudioVolumeUp,
        Scancode::AudioVolumeDown => Keycode::AudioVolumeDown,
        Scancode::AudioVolumeMute => Keycode::AudioVolumeMute,

        Scancode::Escape => Keycode::Escape,
        Scancode::Enter => Keycode::Enter,
        Scancode::Tab => Keycode::Tab,
        Scancode::Space => Keycode::Space,
        Scancode::Backspace => Keycode::Backspace,

        Scancode::CapsLock => Keycode::CapsLock,
        Scancode::MetaLeft => Keycode::MetaLeft,
        Scancode::MetaRight => Keycode::MetaRight,
        Scancode::ShiftLeft => Keycode::ShiftLeft,
        Scancode::ShiftRight => Keycode::ShiftRight,
        Scancode::AltLeft => Keycode::AltLeft,
        Scancode::AltRight => Keycode::AltRight,
        Scancode::ControlLeft => Keycode::ControlLeft,
        Scancode::ControlRight => Keycode::ControlRight,
        Scancode::ContextMenu => Keycode::ContextMenu,

        Scancode::F1 => Keycode::F1,
        Scancode::F2 => Keycode::F2,
        Scancode::F3 => Keycode::F3,
        Scancode::F4 => Keycode::F4,
        Scancode::F5 => Keycode::F5,
        Scancode::F6 => Keycode::F6,
        Scancode::F7 => Keycode::F7,
        Scancode::F8 => Keycode::F8,
        Scancode::F9 => Keycode::F9,
        Scancode::F10 => Keycode::F10,
        Scancode::F11 => Keycode::F11,
        Scancode::F12 => Keycode::F12,

        Scancode::Numlock => Keycode::Numlock,
        Scancode::NumpadMultiply => Keycode::NumpadMultiply,
        Scancode::NumpadAdd => Keycode::NumpadAdd,
        Scancode::NumpadDivide => Keycode::NumpadDivide,
        Scancode::NumpadEnter => Keycode::NumpadEnter,
        Scancode::NumpadSubtract => Keycode::NumpadSubtract,
        Scancode::NumpadEqual => Keycode::NumpadEqual,
        Scancode::NumpadComma => Keycode::NumpadComma,
        Scancode::NumpadDecimal => Keycode::NumpadDecimal,

        Scancode::Numpad0 => Keycode::Numpad0,
        Scancode::Numpad1 => Keycode::Numpad1,
        Scancode::Numpad2 => Keycode::Numpad2,
        Scancode::Numpad3 => Keycode::Numpad3,
        Scancode::Numpad4 => Keycode::Numpad4,
        Scancode::Numpad5 => Keycode::Numpad5,
        Scancode::Numpad6 => Keycode::Numpad6,
        Scancode::Numpad7 => Keycode::Numpad7,
        Scancode::Numpad8 => Keycode::Numpad8,
        Scancode::Numpad9 => Keycode::Numpad9,

        Scancode::ScrollLock => Keycode::ScrollLock,
        Scancode::PrintScreen => Keycode::PrintScreen,
        Scancode::Pause => Keycode::Pause,

        Scancode::Home => Keycode::Home,
        Scancode::Delete => Keycode::Delete,
        Scancode::End => Keycode::End,
        Scancode::PageUp => Keycode::PageUp,
        Scancode::PageDown => Keycode::PageDown,
        Scancode::Insert => Keycode::Insert,

        Scancode::ArrowLeft => Keycode::ArrowLeft,
        Scancode::ArrowUp => Keycode::ArrowUp,
        Scancode::ArrowRight => Keycode::ArrowRight,
        Scancode::ArrowDown => Keycode::ArrowDown,

        // Use localized keys
        _ => match keycode {
            "a" | "A" => return Keycode::A,
            "b" | "B" => return Keycode::B,
            "c" | "C" => return Keycode::C,
            "d" | "D" => return Keycode::D,
            "e" | "E" => return Keycode::E,
            "f" | "F" => return Keycode::F,
            "g" | "G" => return Keycode::G,
            "h" | "H" => return Keycode::H,
            "i" | "I" => return Keycode::I,
            "j" | "J" => return Keycode::J,
            "k" | "K" => return Keycode::K,
            "l" | "L" => return Keycode::L,
            "m" | "M" => return Keycode::M,
            "n" | "N" => return Keycode::N,
            "o" | "O" => return Keycode::O,
            "p" | "P" => return Keycode::P,
            "q" | "Q" => return Keycode::Q,
            "r" | "R" => return Keycode::R,
            "s" | "S" => return Keycode::S,
            "t" | "T" => return Keycode::T,
            "u" | "U" => return Keycode::U,
            "v" | "V" => return Keycode::V,
            "w" | "W" => return Keycode::W,
            "x" | "X" => return Keycode::X,
            "y" | "Y" => return Keycode::Y,
            "z" | "Z" => return Keycode::Z,

            "=" => Keycode::Equal,
            "-" => Keycode::Minus,
            "[" => Keycode::BracketRight,
            "]" => Keycode::BracketLeft,
            "/" => Keycode::Slash,
            "\\" => Keycode::Backslash,

            "'" => Keycode::Quote,
            "`" => Keycode::Backquote,
            ";" => Keycode::Semicolon,
            "," => Keycode::Comma,
            "." => Keycode::Period,

            "&" => Keycode::Ampersand,
            "*" => Keycode::Asterisk,
            "@" => Keycode::At,
            "^" => Keycode::Caret,
            ":" => Keycode::Colon,
            "$" => Keycode::Dollar,
            "!" => Keycode::Exclaim,
            ">" => Keycode::Greater,
            "#" => Keycode::Hash,
            "(" => Keycode::ParenLeft,
            "<" => Keycode::Less,
            "%" => Keycode::Percent,
            "+" => Keycode::Plus,
            "?" => Keycode::Question,
            "\"" => Keycode::QuoteDouble,
            ")" => Keycode::ParenRight,
            "_" => Keycode::Underscore,

            _ => Keycode::Unidentified,
        },
    }
}
