[package]
name = "ct_assetbaker"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"

[[bin]]
path = "src/main_assetbaker.rs"
name = "ct_assetbaker"

[dependencies]
ct_lib = { path = "../ct_lib" }

rayon = "1.5.0"
ico = "0.1.0"
serde = "1.0.118"
