[package]
name = "ct_lib_math"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"

[lib]
path = "src/lib_math.rs"

[dependencies]
num-traits = "0.2.14"
ezing = "0.2.1"
rand = "0.7.3"
rand_pcg = "0.2.1"
serde = "1.0.118"
serde_derive = "1.0.118"
