[package]
name = "ct_lib_audio"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"

[lib]
path = "src/lib_audio.rs"

[dependencies]
ct_lib_core = { path = "../ct_lib_core"}
ct_lib_math = { path = "../ct_lib_math"}

wav = "0.5.0"
serde = "1.0.118"
