[package]
name = "ct_lib"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
glob = "0.3"
ezing = "0.2"
rand = "0.7"
rand_pcg = "0.2"
lodepng = "2.5"
serde = "1.0"
serde_json ="1.0"
serde_derive = "1.0"
bincode = "1.2"
easy_process = "0.1"
audrey = "0.2"
num-traits = "0.2"
hsl = "0.1"
rusttype = "0.8"

