@echo off
REM WARNING: This file was generated by `ct_makeproject` and should not be modified

call web_build.bat 
if %errorlevel% neq 0 (
    echo Something went wrong
    goto :error
)

REM REMOVE DEBUG SYMBOLS
where wasm-strip > nul 2> nul
if %errorlevel% neq 0 (
    echo ERROR: `wasm-strip` not found - download at https://github.com/WebAssembly/wabt
    goto :error
) else (
    wasm-strip target/www/index_bg.wasm
    if %errorlevel% neq 0 goto :error
)

REM OPTIMIZE FILE SIZE
where wasm-opt > nul 2> nul
if %errorlevel% neq 0 (
    echo ERROR: `wasm-opt` not found - download at https://github.com/WebAssembly/binaryen
    goto :error
) else (
    wasm-opt -Oz target/www/index_bg.wasm -o target/www/index_bg.wasm
    if %errorlevel% neq 0 goto :error
)


goto :done

REM ------------------------------------------------------------------------------------------------
:error
echo Failed with error #%errorlevel%.
pause
exit /b %errorlevel%

REM ------------------------------------------------------------------------------------------------
:done
echo FINISHED OPTIMIZING WEB RELEASE BUILD