@echo off
REM WARNING: This file was generated by `ct_makeproject` and should not be modified

REM Install basic HTTP server if not found
where http > nul 2> nul
IF %errorlevel% neq 0 (
    echo Installing basic HTTP server
    cargo install https
)
IF %errorlevel% neq 0 (
    echo ERROR: Could not install basic HTTP server
    goto :error
)

if not exist target mkdir target
pushd target
if not exist www mkdir www
pushd www

http

popd
popd

goto :done 

REM ------------------------------------------------------------------------------------------------
:error
echo Failed with error #%errorlevel%.
pause
exit /b %errorlevel%

REM ------------------------------------------------------------------------------------------------
:done
echo DONE 