@echo off
REM WARNING: This file was generated by `ct_makeproject` and should not be modified

REM Install `wasm-bindgen` if not found
where wasm-bindgen > nul 2> nul
if %errorlevel% neq 0 (
    cargo install wasm-bindgen-cli --version 0.2.69
)
if %errorlevel% neq 0 (
    echo Could not install `wasm-bindgen-cli`
    goto :error
)

REM DEBUG
REM cargo build -p launcher --target wasm32-unknown-unknown
REM if %errorlevel% neq 0 goto :error
REM wasm-bindgen target/wasm32-unknown-unknown/debug/launcher.wasm --out-dir target/www --out-name index --target web
REM if %errorlevel% neq 0 goto :error

REM RELEASE
cargo build --release -p launcher --target wasm32-unknown-unknown
if %errorlevel% neq 0 goto :error
wasm-bindgen target/wasm32-unknown-unknown/release/launcher.wasm --out-dir target/www --out-name index --target web
if %errorlevel% neq 0 goto :error


REM ASSETS
cargo run --package ct_assetbaker
if %errorlevel% neq 0 goto :error

REM NOTE: We remove the directory first or else robovopy trips if there are missing files in the 
REM       original resources directory that we want to copy
rmdir /s /q "target\www\resources"
REM NOTE: robocopy has success error code 1
robocopy "resources" "target\www\resources" /s /e > nul
if %errorlevel% neq 1 (
    REM Repeat in non-silent mode so we get the error message
    robocopy "resources" "target\www\resources" /s /e 
    goto :error
)
copy "launcher\web\index.html" "target\www\index.html" > nul
if %errorlevel% neq 0 (
    REM Repeat in non-silent mode so we get the error
    copy "launcher\web\index.html" "target\www\index.html"
    goto :error
)
copy "launcher\web\manifest.json" "target\www\manifest.json" > nul
if %errorlevel% neq 0 (
    REM Repeat in non-silent mode so we get the error
    copy "launcher\web\manifest.json" "target\www\manifest.json"
    goto :error
)

goto :done

REM ------------------------------------------------------------------------------------------------
:error
echo Failed with error #%errorlevel%.
pause
exit /b %errorlevel%

REM ------------------------------------------------------------------------------------------------
:done
echo FINISHED BUILDING WEB